-- MySQL Script generated by MySQL Workbench
-- Sat Dec 10 19:14:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `doctorId` INT NOT NULL AUTO_INCREMENT,
  `icDoctor` BIGINT NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Famil` VARCHAR(30) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(45) NULL,
  `DR` DATE NULL,
  PRIMARY KEY (`doctorId`, `icDoctor`),
  UNIQUE INDEX `icDoctor_UNIQUE` (`icDoctor` ASC) VISIBLE,
  UNIQUE INDEX `doctorId_UNIQUE` (`doctorId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `icPatient` BIGINT NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Famil` VARCHAR(30) NOT NULL,
  `DR` DATE NOT NULL,
  `Gender` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(100) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(100) NULL,
  PRIMARY KEY (`icPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctorschedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctorschedule` (
  `scheduleId` INT NOT NULL AUTO_INCREMENT,
  `doctorIc` BIGINT NOT NULL,
  `Date` DATE NOT NULL,
  `Day` VARCHAR(15) NOT NULL,
  `Time` TIME NOT NULL,
  `End` TIME NOT NULL,
  `Avaible` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`scheduleId`, `doctorIc`),
  UNIQUE INDEX `scheduleId_UNIQUE` (`scheduleId` ASC) VISIBLE,
  CONSTRAINT `doctorId`
    FOREIGN KEY (`doctorIc`)
    REFERENCES `mydb`.`doctor` (`icDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointment` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `patientIc` BIGINT NOT NULL,
  `scheduleId` INT NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'В процессе',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `patientIc_UNIQUE` (`patientIc` ASC) VISIBLE,
  UNIQUE INDEX `scheduleId_UNIQUE` (`scheduleId` ASC) VISIBLE,
  CONSTRAINT `PatientIc`
    FOREIGN KEY (`patientIc`)
    REFERENCES `mydb`.`patient` (`icPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ScheduleId`
    FOREIGN KEY (`scheduleId`)
    REFERENCES `mydb`.`doctorschedule` (`scheduleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`doctor`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`doctor` (`doctorId`, `icDoctor`, `password`, `Name`, `Famil`, `Address`, `Phone`, `Email`, `DR`) VALUES (1, 123456789, '123', 'Иван', 'Иванов', 'Каширское шоссе', '9385641236', 'Iv@gmail.com', '1989-07-18');
INSERT INTO `mydb`.`doctor` (`doctorId`, `icDoctor`, `password`, `Name`, `Famil`, `Address`, `Phone`, `Email`, `DR`) VALUES (2, 123456788, '12345', 'Петр', 'Петров', 'Улица кошкина', '9872631426', 'Pt@mail.ru', '1977-11-07');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`patient`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`patient` (`icPatient`, `password`, `Name`, `Famil`, `DR`, `Gender`, `Address`, `Phone`, `Email`) VALUES (10, '123', 'Алексей', 'Алексеев', '1991-05-04', 'Мужчина', 'Москва', '9163456889', 'Al@mail.ru');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`doctorschedule`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`doctorschedule` (`scheduleId`, `doctorIc`, `Date`, `Day`, `Time`, `End`, `Avaible`) VALUES (1, 123456789, '2022-12-13', 'Воскрес', '09:00:00', '10:00:00', 'Недоступно');
INSERT INTO `mydb`.`doctorschedule` (`scheduleId`, `doctorIc`, `Date`, `Day`, `Time`, `End`, `Avaible`) VALUES (2, 123456788, '2022-12-13', 'Воскрес', '12:00:00', '13:00:00', 'Доступно');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`appointment`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`appointment` (`Id`, `patientIc`, `scheduleId`, `status`) VALUES (1, 10, 1, 'Завершено');

COMMIT;

-- select * from appointment;
-- select * from doctorschedule;
-- DELETE FROM appointment WHERE Id=1;

-- Delimiter \\
-- Create trigger DeletTab after delete on appointment for each row begin
-- delete from doctorschedule where doctorschedule.scheduleId = old.scheduleId;
-- end \\
-- Delimiter ;
-- select * from doctorschedule;
-- select * from appointment;

-- UPDATE doctorschedule, appointment SET Avaible ="Недоступно" WHERE Id=1 and appointment.scheduleId=doctorschedule.scheduleId;